"""
Deterministic, rule-based exception classification for each SettlementBatch.
Must run after matching.py (needs SettlementBatch.bank_transaction_id / Match rows)
and reads bridge.py's numbers. Every comparison and the suggested_action text below
is fixed Python logic -- nothing here is generated by an LLM.

requires_approval and blocks_reconciliation are not columns on ExceptionRecord --
they're fully determined by classification alone (see CLASSIFICATION_INFO), so they're
derived on demand rather than duplicated into the database.
"""
import datetime
import json
from dataclasses import dataclass
from typing import List, Optional

from sqlalchemy.orm import Session

from app import models, bridge
from app.money import paise_to_rupees

# Set to exact equality (0) rather than a nonzero tolerance -- we have no real
# settlement data exhibiting genuine paisa-level aggregation rounding drift to
# calibrate a production tolerance against. A real deployment processing actual
# multi-line-item settlements might need a small empirically-calibrated tolerance;
# we're not guessing one here without data, same principle as disabling unverified
# refund-rate anomaly detection.
TOLERANCE = 0

# Hardcoded classification -> (requires_approval, blocks_reconciliation, suggested_action).
# Never let an LLM generate or alter this table.
CLASSIFICATION_INFO = {
    "UNMATCHED_BATCH": {
        "requires_approval": True,
        "blocks_reconciliation": True,
        "suggested_action": "Manually investigate — insufficient data to auto-classify.",
    },
    "DUPLICATE_ENTRY": {
        "requires_approval": True,
        "blocks_reconciliation": False,
        "suggested_action": "Remove duplicate settlement entry; confirm no double-posting occurred.",
    },
    "MISSING_REFUND_RECORD": {
        "requires_approval": True,
        "blocks_reconciliation": True,
        "suggested_action": "Add refund entry to internal order record; verify against payment gateway refund log.",
    },
    # Reverse direction from MISSING_REFUND_RECORD: the ORDER record claims a
    # refund the SETTLEMENT never deducted, not the other way around. Kept as a
    # distinct classification rather than folded into MISSING_REFUND_RECORD --
    # this is a genuinely different real-world scenario (a refund logged
    # internally that the payment gateway may never have actually processed,
    # vs. money that left via settlement with no internal record of it), and
    # the two point a human reviewer toward different next actions.
    "REFUND_NOT_IN_SETTLEMENT": {
        "requires_approval": True,
        "blocks_reconciliation": True,
        "suggested_action": (
            "Confirm whether this refund was actually processed by the payment gateway -- "
            "the order record shows a refund this settlement does not reflect. Correct the "
            "internal record if it was not processed, or expect the deduction in a later "
            "settlement if it was."
        ),
    },
    "FEE_TIER_MISMATCH": {
        "requires_approval": True,
        "blocks_reconciliation": True,
        "suggested_action": "Compare charged fee against contracted fee tier; escalate to Razorpay support if confirmed.",
    },
    "UNEXPLAINED_VARIANCE": {
        "requires_approval": True,
        "blocks_reconciliation": True,
        "suggested_action": "Manually investigate — insufficient data to auto-classify.",
    },
    "TIMING_DIFFERENCE": {
        "requires_approval": False,
        "blocks_reconciliation": False,
        "suggested_action": "No action required — settlement date and bank credit date differ due to processing lag.",
    },
    # SYSTEMIC_FEE_DRIFT / SYSTEMIC_REFUND_DRIFT are produced by a separate pass
    # (app/anomaly_detection.py), not by _classify_batch below -- added here only
    # so requires_approval/blocks_reconciliation/suggested_action resolve correctly
    # wherever CLASSIFICATION_INFO is looked up (is_reconciled computation,
    # GET /batches/{id}/exceptions). No existing entry above was changed, and no
    # existing classification logic in this file was touched to add these.
    "SYSTEMIC_FEE_DRIFT": {
        "requires_approval": True,
        "blocks_reconciliation": True,
        "suggested_action": (
            "Review this batch's fee/refund rate against historical pattern — "
            "statistically anomalous even though it reconciles cleanly on its own."
        ),
    },
    "SYSTEMIC_REFUND_DRIFT": {
        "requires_approval": True,
        "blocks_reconciliation": True,
        "suggested_action": (
            "Review this batch's fee/refund rate against historical pattern — "
            "statistically anomalous even though it reconciles cleanly on its own."
        ),
    },
}


@dataclass
class ExceptionResult:
    batch_id: int
    classification: Optional[str]
    requires_approval: bool
    blocks_reconciliation: bool
    suggested_action: Optional[str]
    unexplained_amount: float
    is_reconciled: bool  # True only when classification is None (no exception at all)
    severity: Optional[str] = None  # "high" | "medium" | "low" | "info"


# Severity weighting: a pure, deterministic rule layer on top of classification.
# Does not touch CLASSIFICATION_INFO, requires_approval, blocks_reconciliation, or
# is_reconciled -- those are computed exactly as before. Never let an LLM generate
# or alter this table.
SEVERITY_AMOUNT_THRESHOLD = 1000.0

_FIXED_SEVERITY = {
    "UNMATCHED_BATCH": "high",
    "UNEXPLAINED_VARIANCE": "high",
    "DUPLICATE_ENTRY": "low",
    "TIMING_DIFFERENCE": "info",
}
_AMOUNT_DEPENDENT_SEVERITY = {"MISSING_REFUND_RECORD", "FEE_TIER_MISMATCH", "REFUND_NOT_IN_SETTLEMENT"}


def _compute_severity(classification: str, unexplained_amount: float) -> str:
    if classification in _AMOUNT_DEPENDENT_SEVERITY:
        return "high" if unexplained_amount >= SEVERITY_AMOUNT_THRESHOLD else "medium"
    return _FIXED_SEVERITY[classification]


def _entries_for_batch(db, batch_id):
    return (
        db.query(models.SettlementEntry)
        .filter(models.SettlementEntry.batch_id == batch_id)
        .order_by(models.SettlementEntry.id)
        .all()
    )


def _duplicate_entries(entries):
    """order_ref -> list of entries, for every order_ref that appears more than once."""
    by_ref = {}
    for e in entries:
        by_ref.setdefault(e.order_ref, []).append(e)
    return {ref: es for ref, es in by_ref.items() if len(es) > 1}


def _evidence(*typed_ids):
    """typed_ids: (type_label, id_or_ids_or_None) pairs -> flat JSON-able evidence list."""
    out = []
    for type_label, ids in typed_ids:
        if ids is None:
            continue
        if isinstance(ids, (list, tuple, set)):
            for i in ids:
                out.append({"type": type_label, "id": i})
        else:
            out.append({"type": type_label, "id": ids})
    return out


def _classify_batch(db, batch, match_row, bridge_result):
    """Returns a list of (classification, evidence_list, unexplained_amount) findings.
    A batch can carry more than one independent finding -- e.g. a duplicate entry
    and a missing refund are unrelated problems and neither should mask the other."""
    entries = _entries_for_batch(db, batch.id)

    if batch.bank_transaction_id is None:
        evidence = _evidence(("settlement_entry", [e.id for e in entries]))
        return [("UNMATCHED_BATCH", evidence, abs(batch.total_net))]

    findings = []

    # No rounding needed -- integer paise subtraction is exact, unlike the rupee-float
    # subtraction this used to round via _round2() (removed).
    match_diff = batch.total_net - batch.bank_transaction.amount
    bridge_diff = bridge_result.bridge_net - batch.total_net

    if abs(bridge_diff) > TOLERANCE:
        dupes = _duplicate_entries(entries)
        if dupes:
            dup_entry_ids = [e.id for es in dupes.values() for e in es]
            evidence = _evidence(
                ("settlement_entry", dup_entry_ids),
                ("bank_transaction", batch.bank_transaction_id),
            )
            findings.append(("DUPLICATE_ENTRY", evidence, abs(match_diff)))

    # Entry-vs-OrderRecord consistency check. Deliberately independent of match_diff:
    # a wrongly-tiered fee or an unlogged refund is reflected in what actually got
    # remitted, so it never creates a bank-level variance -- only an internal one,
    # visible only by cross-referencing SettlementEntry against OrderRecord. Every
    # entry is checked (not just the first offender), so unrelated entry-level
    # problems in the same batch are each captured rather than the first masking
    # the rest.
    missing_refund_hits = []  # (entry, order, delta) -- entry.refund > order.refund_amount
    refund_not_in_settlement_hits = []  # (entry, order, delta) -- reverse direction
    fee_mismatch_hits = []  # (entry, order, delta)
    for entry in entries:
        order = (
            db.query(models.OrderRecord)
            .filter(models.OrderRecord.order_ref == entry.order_ref)
            .first()
        )
        if order is None:
            continue

        order_refund = order.refund_amount if order.refund_amount is not None else 0.0
        if entry.refund - order_refund > TOLERANCE:
            missing_refund_hits.append((entry, order, entry.refund - order_refund))
        elif order_refund - entry.refund > TOLERANCE:
            refund_not_in_settlement_hits.append((entry, order, order_refund - entry.refund))

        if abs(entry.fee - order.fee_amount) > TOLERANCE:
            fee_mismatch_hits.append((entry, order, abs(entry.fee - order.fee_amount)))

    if missing_refund_hits:
        evidence = _evidence(
            ("settlement_entry", [e.id for e, _, _ in missing_refund_hits]),
            ("order_record", [o.id for _, o, _ in missing_refund_hits]),
            ("bank_transaction", batch.bank_transaction_id),
        )
        total = sum(d for _, _, d in missing_refund_hits)
        findings.append(("MISSING_REFUND_RECORD", evidence, total))

    if refund_not_in_settlement_hits:
        evidence = _evidence(
            ("settlement_entry", [e.id for e, _, _ in refund_not_in_settlement_hits]),
            ("order_record", [o.id for _, o, _ in refund_not_in_settlement_hits]),
            ("bank_transaction", batch.bank_transaction_id),
        )
        total = sum(d for _, _, d in refund_not_in_settlement_hits)
        findings.append(("REFUND_NOT_IN_SETTLEMENT", evidence, total))

    if fee_mismatch_hits:
        evidence = _evidence(
            ("settlement_entry", [e.id for e, _, _ in fee_mismatch_hits]),
            ("order_record", [o.id for _, o, _ in fee_mismatch_hits]),
            ("bank_transaction", batch.bank_transaction_id),
        )
        total = sum(d for _, _, d in fee_mismatch_hits)
        findings.append(("FEE_TIER_MISMATCH", evidence, total))

    # Catch-all: only when there's an unexplained bank-level variance AND nothing
    # entry-level already accounted for it.
    if (
        abs(match_diff) > TOLERANCE
        and not missing_refund_hits
        and not refund_not_in_settlement_hits
        and not fee_mismatch_hits
    ):
        order_ids = [
            o.id
            for o in db.query(models.OrderRecord)
            .filter(models.OrderRecord.order_ref.in_([e.order_ref for e in entries]))
            .all()
        ]
        evidence = _evidence(
            ("settlement_entry", [e.id for e in entries]),
            ("order_record", order_ids),
            ("bank_transaction", batch.bank_transaction_id),
        )
        findings.append(("UNEXPLAINED_VARIANCE", evidence, abs(match_diff)))

    if (
        match_row is not None
        and match_row.match_type == "fuzzy"
        and abs(match_diff) <= TOLERANCE
        and abs(bridge_diff) <= TOLERANCE
    ):
        evidence = _evidence(("bank_transaction", batch.bank_transaction_id))
        findings.append(("TIMING_DIFFERENCE", evidence, 0.0))

    return findings


def _log_exception_created(db, classification, unexplained_amount, requires_approval):
    # AuditEvent rows are append-only: never update or delete an AuditEvent once written.
    #
    # paise_to_rupees() here is a deliberate, narrow exception to this module
    # staying paise-native throughout (see app/money.py's docstring, which
    # otherwise lists exceptions.py as a module that must never call this):
    # after_state is JSON returned verbatim by GET /audit-trail and rendered
    # directly in the UI (AuditTrail.jsx) -- it's a response boundary like any
    # other, just one that isn't a typed Pydantic model. Found live during a
    # pre-merge regression pass: without this, the audit trail showed e.g.
    # "unexplained Rs.79,934.00" for an exception whose actual amount was
    # Rs.799.34 -- the raw paise integer displayed as if it were already rupees.
    db.add(
        models.AuditEvent(
            timestamp=datetime.datetime.now(),
            actor="system",
            action="exception_created",
            before_state=None,
            after_state=json.dumps(
                {
                    "classification": classification,
                    "unexplained_amount": paise_to_rupees(unexplained_amount),
                    "requires_approval": requires_approval,
                }
            ),
        )
    )


def classify_exceptions(db: Session, batch_ids: Optional[List[int]] = None) -> List[ExceptionResult]:
    """batch_ids: when given, only wipes/reclassifies THOSE batches -- every other
    batch's existing ExceptionRecord rows (including their status, e.g. an already
    "approved" exception, and their cached investigation_result) are left completely
    untouched. Used by the live Razorpay ingestion path (app/razorpay_ingestion.py) so
    ingesting one new event can never destroy the primary dataset's existing exception/
    approval/investigation state. Default (None) is the original full-regen behavior,
    unchanged -- still what app/startup.py, scripts/run_reconciliation.py, and
    app/holdout_sandbox.py all call."""
    # Wipe previous exception rows so this function is safely re-runnable.
    # AuditEvent is NEVER touched here -- it is an append-only audit log.
    exc_query = db.query(models.ExceptionRecord)
    if batch_ids is not None:
        exc_query = exc_query.filter(models.ExceptionRecord.batch_id.in_(batch_ids))
    exc_query.delete(synchronize_session=False)
    db.commit()

    bridge_by_batch = {r.batch_id: r for r in bridge.compute_bridge(db, batch_ids)}
    match_query = db.query(models.Match)
    if batch_ids is not None:
        match_query = match_query.filter(models.Match.settlement_batch_id.in_(batch_ids))
    match_by_batch = {m.settlement_batch_id: m for m in match_query.all()}

    batch_query = db.query(models.SettlementBatch).order_by(models.SettlementBatch.id)
    if batch_ids is not None:
        batch_query = batch_query.filter(models.SettlementBatch.id.in_(batch_ids))

    results = []
    for batch in batch_query.all():
        br = bridge_by_batch[batch.id]
        match_row = match_by_batch.get(batch.id)

        findings = _classify_batch(db, batch, match_row, br)

        if not findings:
            results.append(
                ExceptionResult(
                    batch_id=batch.id,
                    classification=None,
                    requires_approval=False,
                    blocks_reconciliation=False,
                    suggested_action=None,
                    unexplained_amount=0.0,
                    is_reconciled=True,
                )
            )
            continue

        for classification, evidence, unexplained_amount in findings:
            # No rounding needed -- already an exact integer paise value, unlike the
            # rupee-float value this used to round via _round2() (removed).
            info = CLASSIFICATION_INFO[classification]
            requires_approval = info["requires_approval"]
            blocks_reconciliation = info["blocks_reconciliation"]
            suggested_action = info["suggested_action"]
            severity = _compute_severity(classification, unexplained_amount)

            exc = models.ExceptionRecord(
                batch_id=batch.id,
                unexplained_amount=unexplained_amount,
                classification=classification,
                suggested_action=suggested_action,
                status="open",
                linked_evidence_ids=json.dumps(evidence),
                severity=severity,
            )
            db.add(exc)
            db.flush()
            _log_exception_created(db, classification, unexplained_amount, requires_approval)

            results.append(
                ExceptionResult(
                    batch_id=batch.id,
                    classification=classification,
                    requires_approval=requires_approval,
                    blocks_reconciliation=blocks_reconciliation,
                    suggested_action=suggested_action,
                    unexplained_amount=unexplained_amount,
                    is_reconciled=False,
                    severity=severity,
                )
            )

    db.commit()
    return results
