"""
Deterministic, rule-based exception classification for each SettlementBatch.
Must run after matching.py (needs SettlementBatch.bank_transaction_id / Match rows)
and reads bridge.py's numbers. Every comparison and the suggested_action text below
is fixed Python logic -- nothing here is generated by an LLM.

requires_approval and blocks_reconciliation are not columns on ExceptionRecord --
they're fully determined by classification alone (see CLASSIFICATION_INFO), so they're
derived on demand rather than duplicated into the database.
"""
import datetime
import json
from dataclasses import dataclass
from typing import List, Optional

from sqlalchemy.orm import Session

from app import models, bridge

TOLERANCE = 0.01

# Hardcoded classification -> (requires_approval, blocks_reconciliation, suggested_action).
# Never let an LLM generate or alter this table.
CLASSIFICATION_INFO = {
    "UNMATCHED_BATCH": {
        "requires_approval": True,
        "blocks_reconciliation": True,
        "suggested_action": "Manually investigate — insufficient data to auto-classify.",
    },
    "DUPLICATE_ENTRY": {
        "requires_approval": True,
        "blocks_reconciliation": False,
        "suggested_action": "Remove duplicate settlement entry; confirm no double-posting occurred.",
    },
    "MISSING_REFUND_RECORD": {
        "requires_approval": True,
        "blocks_reconciliation": True,
        "suggested_action": "Add refund entry to internal order record; verify against payment gateway refund log.",
    },
    "FEE_TIER_MISMATCH": {
        "requires_approval": True,
        "blocks_reconciliation": True,
        "suggested_action": "Compare charged fee against contracted fee tier; escalate to Razorpay support if confirmed.",
    },
    "UNEXPLAINED_VARIANCE": {
        "requires_approval": True,
        "blocks_reconciliation": True,
        "suggested_action": "Manually investigate — insufficient data to auto-classify.",
    },
    "TIMING_DIFFERENCE": {
        "requires_approval": False,
        "blocks_reconciliation": False,
        "suggested_action": "No action required — settlement date and bank credit date differ due to processing lag.",
    },
}


@dataclass
class ExceptionResult:
    batch_id: int
    classification: Optional[str]
    requires_approval: bool
    blocks_reconciliation: bool
    suggested_action: Optional[str]
    unexplained_amount: float
    is_reconciled: bool  # True only when classification is None (no exception at all)


def _round2(x):
    return round(x, 2)


def _entries_for_batch(db, batch_id):
    return (
        db.query(models.SettlementEntry)
        .filter(models.SettlementEntry.batch_id == batch_id)
        .order_by(models.SettlementEntry.id)
        .all()
    )


def _duplicate_entries(entries):
    """order_ref -> list of entries, for every order_ref that appears more than once."""
    by_ref = {}
    for e in entries:
        by_ref.setdefault(e.order_ref, []).append(e)
    return {ref: es for ref, es in by_ref.items() if len(es) > 1}


def _evidence(*typed_ids):
    """typed_ids: (type_label, id_or_ids_or_None) pairs -> flat JSON-able evidence list."""
    out = []
    for type_label, ids in typed_ids:
        if ids is None:
            continue
        if isinstance(ids, (list, tuple, set)):
            for i in ids:
                out.append({"type": type_label, "id": i})
        else:
            out.append({"type": type_label, "id": ids})
    return out


def _classify_batch(db, batch, match_row, bridge_result):
    """Returns a list of (classification, evidence_list, unexplained_amount) findings.
    A batch can carry more than one independent finding -- e.g. a duplicate entry
    and a missing refund are unrelated problems and neither should mask the other."""
    entries = _entries_for_batch(db, batch.id)

    if batch.bank_transaction_id is None:
        evidence = _evidence(("settlement_entry", [e.id for e in entries]))
        return [("UNMATCHED_BATCH", evidence, abs(batch.total_net))]

    findings = []

    match_diff = _round2(batch.total_net - batch.bank_transaction.amount)
    bridge_diff = _round2(bridge_result.bridge_net - batch.total_net)

    if abs(bridge_diff) > TOLERANCE:
        dupes = _duplicate_entries(entries)
        if dupes:
            dup_entry_ids = [e.id for es in dupes.values() for e in es]
            evidence = _evidence(
                ("settlement_entry", dup_entry_ids),
                ("bank_transaction", batch.bank_transaction_id),
            )
            findings.append(("DUPLICATE_ENTRY", evidence, abs(match_diff)))

    # Entry-vs-OrderRecord consistency check. Deliberately independent of match_diff:
    # a wrongly-tiered fee or an unlogged refund is reflected in what actually got
    # remitted, so it never creates a bank-level variance -- only an internal one,
    # visible only by cross-referencing SettlementEntry against OrderRecord. Every
    # entry is checked (not just the first offender), so unrelated entry-level
    # problems in the same batch are each captured rather than the first masking
    # the rest.
    missing_refund_hits = []  # (entry, order, delta)
    fee_mismatch_hits = []  # (entry, order, delta)
    for entry in entries:
        order = (
            db.query(models.OrderRecord)
            .filter(models.OrderRecord.order_ref == entry.order_ref)
            .first()
        )
        if order is None:
            continue

        order_refund = order.refund_amount if order.refund_amount is not None else 0.0
        if entry.refund - order_refund > TOLERANCE:
            missing_refund_hits.append((entry, order, entry.refund - order_refund))

        if abs(entry.fee - order.fee_amount) > TOLERANCE:
            fee_mismatch_hits.append((entry, order, abs(entry.fee - order.fee_amount)))

    if missing_refund_hits:
        evidence = _evidence(
            ("settlement_entry", [e.id for e, _, _ in missing_refund_hits]),
            ("order_record", [o.id for _, o, _ in missing_refund_hits]),
            ("bank_transaction", batch.bank_transaction_id),
        )
        total = _round2(sum(d for _, _, d in missing_refund_hits))
        findings.append(("MISSING_REFUND_RECORD", evidence, total))

    if fee_mismatch_hits:
        evidence = _evidence(
            ("settlement_entry", [e.id for e, _, _ in fee_mismatch_hits]),
            ("order_record", [o.id for _, o, _ in fee_mismatch_hits]),
            ("bank_transaction", batch.bank_transaction_id),
        )
        total = _round2(sum(d for _, _, d in fee_mismatch_hits))
        findings.append(("FEE_TIER_MISMATCH", evidence, total))

    # Catch-all: only when there's an unexplained bank-level variance AND nothing
    # entry-level already accounted for it.
    if abs(match_diff) > TOLERANCE and not missing_refund_hits and not fee_mismatch_hits:
        order_ids = [
            o.id
            for o in db.query(models.OrderRecord)
            .filter(models.OrderRecord.order_ref.in_([e.order_ref for e in entries]))
            .all()
        ]
        evidence = _evidence(
            ("settlement_entry", [e.id for e in entries]),
            ("order_record", order_ids),
            ("bank_transaction", batch.bank_transaction_id),
        )
        findings.append(("UNEXPLAINED_VARIANCE", evidence, abs(match_diff)))

    if (
        match_row is not None
        and match_row.match_type == "fuzzy"
        and abs(match_diff) <= TOLERANCE
        and abs(bridge_diff) <= TOLERANCE
    ):
        evidence = _evidence(("bank_transaction", batch.bank_transaction_id))
        findings.append(("TIMING_DIFFERENCE", evidence, 0.0))

    return findings


def _log_exception_created(db, classification, unexplained_amount, requires_approval):
    # AuditEvent rows are append-only: never update or delete an AuditEvent once written.
    db.add(
        models.AuditEvent(
            timestamp=datetime.datetime.now(),
            actor="system",
            action="exception_created",
            before_state=None,
            after_state=json.dumps(
                {
                    "classification": classification,
                    "unexplained_amount": unexplained_amount,
                    "requires_approval": requires_approval,
                }
            ),
        )
    )


def classify_exceptions(db: Session) -> List[ExceptionResult]:
    # Wipe previous exception rows so this function is safely re-runnable.
    # AuditEvent is NEVER touched here -- it is an append-only audit log.
    db.query(models.ExceptionRecord).delete()
    db.commit()

    bridge_by_batch = {r.batch_id: r for r in bridge.compute_bridge(db)}
    match_by_batch = {m.settlement_batch_id: m for m in db.query(models.Match).all()}

    results = []
    for batch in db.query(models.SettlementBatch).order_by(models.SettlementBatch.id).all():
        br = bridge_by_batch[batch.id]
        match_row = match_by_batch.get(batch.id)

        findings = _classify_batch(db, batch, match_row, br)

        if not findings:
            results.append(
                ExceptionResult(
                    batch_id=batch.id,
                    classification=None,
                    requires_approval=False,
                    blocks_reconciliation=False,
                    suggested_action=None,
                    unexplained_amount=0.0,
                    is_reconciled=True,
                )
            )
            continue

        for classification, evidence, unexplained_amount in findings:
            unexplained_amount = _round2(unexplained_amount)
            info = CLASSIFICATION_INFO[classification]
            requires_approval = info["requires_approval"]
            blocks_reconciliation = info["blocks_reconciliation"]
            suggested_action = info["suggested_action"]

            exc = models.ExceptionRecord(
                batch_id=batch.id,
                unexplained_amount=unexplained_amount,
                classification=classification,
                suggested_action=suggested_action,
                status="open",
                linked_evidence_ids=json.dumps(evidence),
            )
            db.add(exc)
            db.flush()
            _log_exception_created(db, classification, unexplained_amount, requires_approval)

            results.append(
                ExceptionResult(
                    batch_id=batch.id,
                    classification=classification,
                    requires_approval=requires_approval,
                    blocks_reconciliation=blocks_reconciliation,
                    suggested_action=suggested_action,
                    unexplained_amount=unexplained_amount,
                    is_reconciled=False,
                )
            )

    db.commit()
    return results
